### ISSUE TITLE
input placeholder text has low contrast

### ISSUE THREAD

**Issue by raboof** [apache/security-vulnogram#143]
The 'placeholder text' for inputs is the default light gray, which can hard to see. Perhaps we should style it as green and italic?

**Comment by martin-g** [comment]
E.g. `Advisory ID`'s placeholder text is hard to read:
![lightgrey-placeholders](https://github.com/apache/security-vulnogram/assets/232002/7d666465-f5e1-44d2-b115-4a0840f70788)
