### ISSUE TITLE
Comment emails HTML but Content-Type: text/plain

### ISSUE THREAD

**Issue by raboof** [apache/security-vulnogram#71]
Leading to mailclients showing you the HTML tags.

**Comment by raboof** [comment]
We have a couple of options:
* Send HTML-only email (I don't think we want that (?))
* Send Multipart email (that seems more trouble than it's worth)
* Turn this field back into a plaintext field
* Convert the rich text comment into plaintext for the email

The conversion from the rich text boxes to plain text is not perfect, but it is also used for the notification emails, so I'm going for "Convert the rich text comment into plaintext" - over time we can hopefully improve that conversion.

**Comment by iamamoose** [comment]
> * Turn this field back into a plaintext field

+1 on this
